FROM golang:1.17.3-alpine3.13 AS tyk-test-custom-builder
WORKDIR /go/src/app

# Prepare dependencies
COPY go.mod ./
RUN go mod download

COPY . .
RUN go build

FROM alpine:3.15.0

COPY --from=tyk-test-custom-builder /go/src/app/tyk-test-custom .
CMD ["./tyk-test-custom"]